### ISSUE TITLE
VPN only not detected properly

### ISSUE THREAD

**Issue by tango25001** [ArrowOS/android_manifest#10]
Hello, I am using Arrow OS on a MotoG5plus. 
Is it possible to have the Rom check vor VPN-Only connections. 

At the moment when I use Wifi/4G or Ethernet-OTG the network-speed Symbol is displayed and everything runs fine.

When I use a VPN-Only connection (Device in Flightmode and VPN over Gnirehtet https://github.com/Genymobile/gnirehtet), 
the network is not detected, although Internet is available. (Firefox works fine, but most of the Rom-Features think that they are offline).

Could you please add checking for VPN-Only connections. 
This would be awesome
thank you very much

**Comment by kubersharma001** [comment]
I think this was fixed a few months back and this is also a wrong place for putting up these issues, anyways.
